### ISSUE TITLE
Top-level, one-line multi-variable declaration loses variables after the first

### ISSUE THREAD

**Issue by aheber** [xixiaofinland/afmt#7]
Only on class-level objects. If you use the syntax to define multiple variables of the same type, only the first is being printed.

Example:
```apex
class Me {
  Integer testVal = 1, anotherVal = 0;
}
```

Formatted Output:
```apex
class Me {
  Integer testVal = 1;
}
```

Parse tree:
```
field_declaration [1, 2] - [1, 38]
  type: type_identifier [1, 2] - [1, 9]
  declarator: variable_declarator [1, 10] - [1, 21]
    name: identifier [1, 10] - [1, 17]
    assignment_operator [1, 18] - [1, 19]
    value: int [1, 20] - [1, 21]
  declarator: variable_declarator [1, 23] - [1, 37]
    name: identifier [1, 23] - [1, 33]
    assignment_operator [1, 34] - [1, 35]
    value: int [1, 36] - [1, 37]
```

For contrast, this formats correctly and doesn't lose anything:
```apex
class Me {
  void method1() {
    Integer testVal = 1, anotherVal = 0;
  }
}
```

**Comment by xixiaofinland** [comment]
good catch! One node is named "field_declaration", the other is "local_variable_declaration". Despite almost the same, they are implemented in different methods.

This is fixed in v0.0.13, and [the new test file](https://github.com/xixiaofinland/afmt/blob/main/tests/prettier80/variableDeclarator.in) guards it.
